/*
 * The MIT License
 *
 * Copyright 2014 Goblom.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.goblom.bukkitlibs.item;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

/**
 *
 * @author Goblom
 */
public class Items {

    private static final List<Items> items = new ArrayList();

    public static final Items AIR = new Items("0", "Air", new ItemStack(Material.AIR));
    public static final Items STONE = new Items("1", "Stone", new ItemStack(Material.STONE));
    public static final Items GRANITE = new Items("1:1", "Granite", new ItemStack(Material.STONE, 1, (short) 1));
    public static final Items POLISHED_GRANITE = new Items("1:2", "Polished Granite", new ItemStack(Material.STONE, 1, (short) 2));
    public static final Items DIORITE = new Items("1:3", "Diorite", new ItemStack(Material.STONE, 1, (short) 3));
    public static final Items POLISHED_DIORITE = new Items("1:4", "Polished Diorite", new ItemStack(Material.STONE, 1, (short) 4));
    public static final Items ANDESITE = new Items("1:5", "Andesite", new ItemStack(Material.STONE, 1, (short) 5));
    public static final Items POLISHED_ANDESITE = new Items("1:6", "Polished Andesite", new ItemStack(Material.STONE, 1, (short) 5));
    public static final Items GRASS_BLOCK = new Items("2", "Grass Block", new ItemStack(Material.GRASS));
    public static final Items DIRT = new Items("3", "Dirt", new ItemStack(Material.DIRT));
    public static final Items COARSE_DIRT = new Items("3:1", "Coarse Dirt", new ItemStack(Material.DIRT, 1, (short) 1));
    public static final Items PODZOL = new Items("3:2", "Podzol", new ItemStack(Material.DIRT, 1, (short) 2));
    public static final Items COBBLESTONE = new Items("4", "Cobblestone", new ItemStack(Material.COBBLESTONE));
    public static final Items OAK_WOOD_PLANKS = new Items("5", "Oad Wood Planks");
    public static final Items SPRUCE_WOOD_PLANKS = new Items("5:1", "Spruce Wood Planks");
    public static final Items BIRCH_WOOD_PLANKS = new Items("5:2", "Birch Wood Planks");
    public static final Items JUNGLE_WOOD_PLANKS = new Items("5:3", "Jungle Wood Planks");
    public static final Items ACACIA_WOOD_PLANKS = new Items("5:4", "Acacia Wood Planks");
    public static final Items DARK_OAK_WOOD_PLANKS = new Items("5:5", "Dark Oak Wood Planks");
    public static Items OAK_SAPLING = new Items("6", "Oak Sapling");
    public static Items SPRUCE_SAPLING = new Items("6:1", "Spruce Sapling");
    public static Items BIRCH_SAPLING = new Items("6:2", "Birch Sapling");
    public static Items JUNGLE_SAPLING = new Items("6:3", "Jungle Sapling");
    public static Items ACACIA_SAPLING = new Items("6:4", "Acacia Sapling");
    public static Items DARK_OAK_SAPLING = new Items("6:5", "Dark Oak Sapling");
    public static Items BEDROCK = new Items("7", "Bedrock");
    static {
        ImmutableList.<Items>builder()
                .add(new Items("8", "Water (No Spread)"))
                .add(new Items("9", "Water"))
                .add(new Items("10", "Lava (No Spread)"))
                .add(new Items("11", "Lava"))
                .add(new Items("12", "Sand"))
                .add(new Items("13", "Gravel"))
                .add(new Items("14", "Gold Ore"))
                .add(new Items("15", "Iron Ore"))
                .add(new Items("16", "Coal Ore"))
                .add(new Items("17", "Oak Wood"))
                .add(new Items("17:1", "Spruce Wood"))
                .add(new Items("17:2", "Birch Wood"))
                .add(new Items("17:3", "Jungle Wood"))
                .add(new Items("18", "Oak Leaves"))
                .add(new Items("18:1", "Spruce Leaves"))
                .add(new Items("18:2", "Birch Leaves"))
                .add(new Items("18:3", "Jungle Leaves"))
                .add(new Items("19", "Sponge"))
                .add(new Items("20", "Glass"))
                .add(new Items("21", "Lapis Lazuli Ore"))
                .add(new Items("22", "Lapis Lazuli Block"))
                .add(new Items("23", "Dispenser"))
                .add(new Items("24", "Sandstone"))
                .add(new Items("24:1", "Chiseled Sandstone"))
                .add(new Items("24:2", "Smooth Sandstone"))
                .add(new Items("25", "Note Block"))
                .add(new Items("26", "Bed"))
                .add(new Items("27", "Powered Rail"))
                .add(new Items("28", "Detector Rail"))
                .add(new Items("29", "Sticky Piston"))
                .add(new Items("30", "Web"))
                .add(new Items("31", "Shrub"))
                .add(new Items("31:1", "Grass"))
                .add(new Items("31:2", "Fern"))
                .add(new Items("32", "Dead Bush"))
                .add(new Items("33", "Piston"))
                .add(new Items("34", "Piston (Head)"))
                .add(new Items("35", "Wool"))
                .add(new Items("35:1", "Orange Wool"))
                .add(new Items("35:2", "Magenta Wool"))
                .add(new Items("35:3", "Light Blue Wool"))
                .add(new Items("35:4", "Yellow Wool"))
                .add(new Items("35:5", "Lime Wool"))
                .add(new Items("35:6", "Pink Wool"))
                .add(new Items("35:7", "Gray Wool"))
                .add(new Items("35:8", "Light Gray Wool"))
                .add(new Items("35:9", "Cyan Wool"))
                .add(new Items("35:10", "Purple Wool"))
                .add(new Items("35:11", "Blue Wool"))
                .add(new Items("35:12", "Brown Wool"))
                .add(new Items("35:13", "Green Wool"))
                .add(new Items("35:14", "Red Wool"))
                .add(new Items("35:15", "Black Wool"))
                .add(new Items("37", "Dandelion"))
                .add(new Items("38", "Rose"))
                .add(new Items("39", "Brown Mushroom"))
                .add(new Items("40", "Red Mushroom"))
                .add(new Items("41", "Gold Block"))
                .add(new Items("42", "Iron Block"))
                .add(new Items("43", "Stone Slab (Double)"))
                .add(new Items("43:1", "Sandstone Slab (Double)"))
                .add(new Items("43:2", "Wooden Slab (Double)"))
                .add(new Items("43:3", "Cobblestone Slab (Double)"))
                .add(new Items("43:4", "Brick Slab (Double)"))
                .add(new Items("43:5", "Stone Brick Slab (Double)"))
                .add(new Items("44", "Stone Slab"))
                .add(new Items("44:1", "Sandstone Slab"))
                .add(new Items("44:2", "Wooden Slab"))
                .add(new Items("44:3", "Cobblestone Slab"))
                .add(new Items("44:4", "Brick Slab"))
                .add(new Items("44:5", "Stone Brick Slab"))
                .add(new Items("44:6", "Nether Brick Slab"))
                .add(new Items("44:7", "Quartz Slab"))
                .add(new Items("45", "Brick"))
                .add(new Items("46", "TNT"))
                .add(new Items("47", "Bookcase"))
                .add(new Items("48", "Moss Stone"))
                .add(new Items("49", "Obsidian"))
                .add(new Items("50", "Torch"))
                .add(new Items("51", "Fire"))
                .add(new Items("52", "Mob Spawner"))
                .add(new Items("53", "Oak Wood Stairs"))
                .add(new Items("54", "Chest"))
                .add(new Items("55", "Redstone Wire"))
                .add(new Items("56", "Diamond Ore"))
                .add(new Items("57", "Diamond Block"))
                .add(new Items("58", "Crafting Table"))
                .add(new Items("59", "Wheat (Crop)"))
                .add(new Items("60", "Farmland"))
                .add(new Items("61", "Furnace"))
                .add(new Items("62", "Furnace (Smelting)"))
                .add(new Items("63", "Sign (Block)"))
                .add(new Items("64", "Wood Door (Block)"))
                .add(new Items("65", "Ladder"))
                .add(new Items("66", "Rails"))
                .add(new Items("67", "Stone Stairs"))
                .add(new Items("68", "Sign (Wall Block)"))
                .add(new Items("69", "Lever"))
                .add(new Items("70", "Pressure Plate"))
                .add(new Items("71", "Iron Door (Block)"))
                .add(new Items("72", "Pressure Plate"))
                .add(new Items("73", "Redstone Ore"))
                .add(new Items("74", "Redstone Ore (Glowing)"))
                .add(new Items("75", "Redstone Torch (Off)"))
                .add(new Items("76", "Redstone Torch"))
                .add(new Items("77", "Button"))
                .add(new Items("78", "Snow"))
                .add(new Items("79", "Ice"))
                .add(new Items("80", "Snow Block"))
                .add(new Items("81", "Cactus"))
                .add(new Items("82", "Clay Block"))
                .add(new Items("83", "Sugar Cane (Block)"))
                .add(new Items("84", "Jukebox"))
                .add(new Items("85", "Fence"))
                .add(new Items("86", "Pumpkin"))
                .add(new Items("87", "Netherrack"))
                .add(new Items("88", "Soul Sand"))
                .add(new Items("89", "Glowstone"))
                .add(new Items("90", "Portal"))
                .add(new Items("91", "Jack-O-Lantern"))
                .add(new Items("92", "Cake (Block)"))
                .add(new Items("93", "Redstone Repeater (Block Off)"))
                .add(new Items("94", "Redstone Repeater (Block On)"))
                .add(new Items("95", "Stained Glass"))
                .add(new Items("96", "Trapdoor"))
                .add(new Items("97", "Silverfish Stone"))
                .add(new Items("98", "Stone Bricks"))
                .add(new Items("98:1", "Mossy Stone Bricks"))
                .add(new Items("98:2", "Cracked Stone Bricks"))
                .add(new Items("99", "Brown Mushroom (Block)"))
                .add(new Items("100", "Red Mushroom (Block)"))
                .add(new Items("101", "Iron Bars"))
                .add(new Items("102", "Glass Pane"))
                .add(new Items("103", "Melon (Block)"))
                .add(new Items("104", "Pumpkin Vine"))
                .add(new Items("105", "Melon Vine"))
                .add(new Items("106", "Vines"))
                .add(new Items("107", "Fence Gate"))
                .add(new Items("108", "Brick Stairs"))
                .add(new Items("109", "Stone Brick Stairs"))
                .add(new Items("110", "Mycelium"))
                .add(new Items("111", "Lily Pad"))
                .add(new Items("112", "Nether Brick"))
                .add(new Items("113", "Nether Brick Fence"))
                .add(new Items("114", "Nether Brick Stairs"))
                .add(new Items("115", "Nether Wart"))
                .add(new Items("116", "Enchantment Table"))
                .add(new Items("117", "Brewing Stand (Block)"))
                .add(new Items("118", "Cauldron (Block)"))
                .add(new Items("119", "End Portal"))
                .add(new Items("120", "End Portal Frame"))
                .add(new Items("121", "End Stone"))
                .add(new Items("122", "Dragon Egg"))
                .add(new Items("123", "Redstone Lamp (Inactive)"))
                .add(new Items("124", "Redstone Lamp (Active)"))
                .add(new Items("125", "Double Wood Slab"))
                .add(new Items("126", "Oak Wood Slab"))
                .add(new Items("126:1", "Spruce Wood Slab"))
                .add(new Items("126:2", "Birch Slab"))
                .add(new Items("126:3", "Jungle Slab"))
                .add(new Items("126:4", "Acacia Wood Slab"))
                .add(new Items("126:5", "Dark Oak Wood Slab"))
                .add(new Items("127", "Cocoa Plant"))
                .add(new Items("128", "Sandstone Stairs"))
                .add(new Items("129", "Emerald Ore"))
                .add(new Items("130", "Ender Chest"))
                .add(new Items("131", "Tripwire Hook"))
                .add(new Items("132", "Tripwire"))
                .add(new Items("133", "Emerald Block"))
                .add(new Items("134", "Spruce Wood Stairs"))
                .add(new Items("135", "Birch Wood Stairs"))
                .add(new Items("136", "Jungle Wood Stairs"))
                .add(new Items("137", "Command Block"))
                .add(new Items("138", "Beacon Block"))
                .add(new Items("139", "Cobblestone Wall"))
                .add(new Items("139:1", "Mossy Cobblestone Wall"))
                .add(new Items("140", "Flower Pot"))
                .add(new Items("141", "Carrots"))
                .add(new Items("142", "Potatoes"))
                .add(new Items("143", "Button"))
                .add(new Items("144", "Head"))
                .add(new Items("145", "Anvil"))
                .add(new Items("146", "Trapped Chest"))
                .add(new Items("147", "Weighted Pressure Plate (Light)"))
                .add(new Items("148", "Weighted Pressure Plate (Heavy)"))
                .add(new Items("149", "Redstone Comparator (inactive)"))
                .add(new Items("150", "Redstone Comparator (active)"))
                .add(new Items("151", "Daylight Sensor"))
                .add(new Items("152", "Redstone Block"))
                .add(new Items("153", "Nether Quartz Ore"))
                .add(new Items("154", "Hopper"))
                .add(new Items("155", "Quartz Block"))
                .add(new Items("155:1", "Chiseled Quartz Block"))
                .add(new Items("155:2", "Pillar Quartz Block"))
                .add(new Items("156", "Quartz Stairs"))
                .add(new Items("157", "Activator Rail"))
                .add(new Items("158", "Dropper"))
                .add(new Items("159", "Stained Clay"))
                .add(new Items("160", "Stained Glass Pane"))
                .add(new Items("161:0", "Acacia Leaves"))
                .add(new Items("161:1", "Dark Oak Leaves"))
                .add(new Items("162:0", "Acacia Wood"))
                .add(new Items("162:1", "Dark Oak Wood"))
                .add(new Items("163", "Acacia Wood Stairs"))
                .add(new Items("164", "Dark Oak Wood Stairs"))
                .add(new Items("165", "Slime Block"))
                .add(new Items("166", "Barrier"))
                .add(new Items("167", "Iron Trapdoor"))
                .add(new Items("168", "Prismarine"))
                .add(new Items("169", "Sea Lantern"))
                .add(new Items("170", "Hay Block"))
                .add(new Items("171", "Carpet"))
                .add(new Items("172", "Hardened Clay"))
                .add(new Items("173", "Block of Coal"))
                .add(new Items("174", "Packed Ice"))
                .add(new Items("175:0", "Sunflower"))
                .add(new Items("175:1", "Lilac"))
                .add(new Items("175:2", "Double Tallgrass"))
                .add(new Items("175:3", "Large Fern"))
                .add(new Items("175:4", "Rose Bush"))
                .add(new Items("175:5", "Peony"))
                .add(new Items("256", "Iron Shovel"))
                .add(new Items("257", "Iron Pickaxe"))
                .add(new Items("258", "Iron Axe"))
                .add(new Items("259", "Flint and Steel"))
                .add(new Items("260", "Apple"))
                .add(new Items("261", "Bow"))
                .add(new Items("262", "Arrow"))
                .add(new Items("263", "Coal"))
                .add(new Items("263:1", "Charcoal"))
                .add(new Items("264", "Diamond"))
                .add(new Items("265", "Iron Ingot"))
                .add(new Items("266", "Gold Ingot"))
                .add(new Items("267", "Iron Sword"))
                .add(new Items("268", "Wooden Sword"))
                .add(new Items("269", "Wooden Shovel"))
                .add(new Items("270", "Wooden Pickaxe"))
                .add(new Items("271", "Wooden Axe"))
                .add(new Items("272", "Stone Sword"))
                .add(new Items("273", "Stone Shovel"))
                .add(new Items("274", "Stone Pickaxe"))
                .add(new Items("275", "Stone Axe"))
                .add(new Items("276", "Diamond Sword"))
                .add(new Items("277", "Diamond Shovel"))
                .add(new Items("278", "Diamond Pickaxe"))
                .add(new Items("279", "Diamond Axe"))
                .add(new Items("280", "Stick"))
                .add(new Items("281", "Bowl"))
                .add(new Items("282", "Mushroom Stew"))
                .add(new Items("283", "Gold Sword"))
                .add(new Items("284", "Gold Shovel"))
                .add(new Items("285", "Gold Pickaxe"))
                .add(new Items("286", "Gold Axe"))
                .add(new Items("287", "String"))
                .add(new Items("288", "Feather"))
                .add(new Items("289", "Gunpowder"))
                .add(new Items("290", "Wooden Hoe"))
                .add(new Items("291", "Stone Hoe"))
                .add(new Items("292", "Iron Hoe"))
                .add(new Items("293", "Diamond Hoe"))
                .add(new Items("294", "Gold Hoe"))
                .add(new Items("295", "Seeds"))
                .add(new Items("296", "Wheat"))
                .add(new Items("297", "Bread"))
                .add(new Items("298", "Leather Helmet"))
                .add(new Items("299", "Leather Chestplate"))
                .add(new Items("300", "Leather Leggings"))
                .add(new Items("301", "Leather Boots"))
                .add(new Items("302", "Chainmail Helmet"))
                .add(new Items("303", "Chainmail Chestplate"))
                .add(new Items("304", "Chainmail Leggings"))
                .add(new Items("305", "Chainmail Boots"))
                .add(new Items("306", "Iron Helmet"))
                .add(new Items("307", "Iron Chestplate"))
                .add(new Items("308", "Iron Leggings"))
                .add(new Items("309", "Iron Boots"))
                .add(new Items("310", "Diamond Helmet"))
                .add(new Items("311", "Diamond Chestplate"))
                .add(new Items("312", "Diamond Leggings"))
                .add(new Items("313", "Diamond Boots"))
                .add(new Items("314", "Gold Helmet"))
                .add(new Items("315", "Gold Chestplate"))
                .add(new Items("316", "Gold Leggings"))
                .add(new Items("317", "Gold Boots"))
                .add(new Items("318", "Flint"))
                .add(new Items("319", "Raw Porkchop"))
                .add(new Items("320", "Cooked Porkchop"))
                .add(new Items("321", "Painting"))
                .add(new Items("322", "Gold Apple"))
                .add(new Items("323", "Sign"))
                .add(new Items("324", "Wooden Door"))
                .add(new Items("325", "Bucket"))
                .add(new Items("326", "Water Bucket"))
                .add(new Items("327", "Lava Bucket"))
                .add(new Items("328", "Minecart"))
                .add(new Items("329", "Saddle"))
                .add(new Items("330", "Iron Door"))
                .add(new Items("331", "Redstone"))
                .add(new Items("332", "Snowball"))
                .add(new Items("333", "Boat"))
                .add(new Items("334", "Leather"))
                .add(new Items("335", "Milk Bucket"))
                .add(new Items("336", "Brick"))
                .add(new Items("337", "Clay"))
                .add(new Items("338", "Sugar Cane"))
                .add(new Items("339", "Paper"))
                .add(new Items("340", "Book"))
                .add(new Items("341", "Slime Ball"))
                .add(new Items("342", "Storage Minecart"))
                .add(new Items("343", "Powered Minecart"))
                .add(new Items("344", "Egg"))
                .add(new Items("345", "Compass"))
                .add(new Items("346", "Fishing Rod"))
                .add(new Items("347", "Watch"))
                .add(new Items("348", "Glowstone Dust"))
                .add(new Items("349", "Raw Fish"))
                .add(new Items("349:1", "Raw Salmon"))
                .add(new Items("349:2", "Clownfish"))
                .add(new Items("349:3", "Pufferfish"))
                .add(new Items("350", "Cooked Fish"))
                .add(new Items("350:1", "Cooked Salmon"))
                .add(new Items("351", "Ink Sack [Black Dye]"))
                .add(new Items("351:1", "Rose Red [Red Dye]"))
                .add(new Items("351:2", "Cactus Green [Green Dye]"))
                .add(new Items("351:3", "Cocoa Bean [Brown Dye]"))
                .add(new Items("351:4", "Lapis Lazuli [Blue Dye]"))
                .add(new Items("351:5", "Purple Dye"))
                .add(new Items("351:6", "Cyan Dye"))
                .add(new Items("351:7", "Light Gray Dye"))
                .add(new Items("351:8", "Gray Dye"))
                .add(new Items("351:9", "Pink Dye"))
                .add(new Items("351:10", "Lime Dye"))
                .add(new Items("351:11", "Dandelion Yellow [Yellow Dye]"))
                .add(new Items("351:12", "Light Blue Dye"))
                .add(new Items("351:13", "Magenta Dye"))
                .add(new Items("351:14", "Orange Dye"))
                .add(new Items("351:15", "Bone Meal [White Dye]"))
                .add(new Items("352", "Bone"))
                .add(new Items("353", "Sugar"))
                .add(new Items("354", "Cake"))
                .add(new Items("355", "Bed"))
                .add(new Items("356", "Redstone Repeater"))
                .add(new Items("357", "Cookie"))
                .add(new Items("358", "Map"))
                .add(new Items("359", "Shears"))
                .add(new Items("360", "Melon"))
                .add(new Items("361", "Pumpkin Seeds"))
                .add(new Items("362", "Melon Seeds"))
                .add(new Items("363", "Raw Beef"))
                .add(new Items("364", "Steak"))
                .add(new Items("365", "Raw Chicken"))
                .add(new Items("366", "Roast Chicken"))
                .add(new Items("367", "Rotten Flesh"))
                .add(new Items("368", "Ender Pearl"))
                .add(new Items("369", "Blaze Rod"))
                .add(new Items("370", "Ghast Tear"))
                .add(new Items("371", "Gold Nugget"))
                .add(new Items("372", "Nether Wart"))
                .add(new Items("373", "Water Bottle"))
                .add(new Items("373:16", "Awkward Potion"))
                .add(new Items("373:32", "Thick Potion"))
                .add(new Items("373:64", "Mundane Potion"))
                .add(new Items("373:8193", "Regeneration Potion (0:45)"))
                .add(new Items("373:8194", "Swiftness Potion (3:00)"))
                .add(new Items("373:8195", "Fire Resistance Potion (3:00)"))
                .add(new Items("373:8196", "Poison Potion (0:45)"))
                .add(new Items("373:8197", "Healing Potion"))
                .add(new Items("373:8200", "Weakness Potion (1:30)"))
                .add(new Items("373:8201", "Strength Potion (3:00)"))
                .add(new Items("373:8202", "Slowness Potion (1:30)"))
                .add(new Items("373:8204", "Harming Potion"))
                .add(new Items("373:8225", "Regeneration Potion II (0:22)"))
                .add(new Items("373:8226", "Swiftness Potion II (1:30)"))
                .add(new Items("373:8228", "Poison Potion II (0:22)"))
                .add(new Items("373:8229", "Healing Potion II"))
                .add(new Items("373:8230", "Night Vision Potion (3:00)"))
                .add(new Items("373:8233", "Strength Potion II (1:30)"))
                .add(new Items("373:8236", "Harming Potion II"))
                .add(new Items("373:8237", "Water Breathing Potion (3:00)"))
                .add(new Items("373:8238", "Invisibility Potion (3:00)"))
                .add(new Items("373:8257", "Regeneration Potion (2:00)"))
                .add(new Items("373:8258", "Swiftness Potion (8:00)"))
                .add(new Items("373:8259", "Fire Resistance Potion (8:00)"))
                .add(new Items("373:8260", "Poison Potion (2:00)"))
                .add(new Items("373:8262", "Night Vision Potion (8:00)"))
                .add(new Items("373:8264", "Weakness Potion (4:00)"))
                .add(new Items("373:8265", "Strength Potion (8:00)"))
                .add(new Items("373:8266", "Slowness Potion (4:00)"))
                .add(new Items("373:8269", "Water Breathing Potion (8:00)"))
                .add(new Items("373:8270", "Invisibility Potion (8:00)"))
                .add(new Items("373:16378", "Fire Resistance Splash (2:15)"))
                .add(new Items("373:16385", "Regeneration Splash (0:33)"))
                .add(new Items("373:16386", "Swiftness Splash (2:15)"))
                .add(new Items("373:16388", "Poison Splash (0:33)"))
                .add(new Items("373:16389", "Healing Splash"))
                .add(new Items("373:16392", "Weakness Splash (1:07)"))
                .add(new Items("373:16393", "Strength Splash (2:15)"))
                .add(new Items("373:16394", "Slowness Splash (1:07)"))
                .add(new Items("373:16396", "Harming Splash"))
                .add(new Items("373:16418", "Swiftness Splash II (1:07)"))
                .add(new Items("373:16420", "Poison Splash II (0:16)"))
                .add(new Items("373:16421", "Healing Splash II"))
                .add(new Items("373:16422", "Night Vision Splash (2:15)"))
                .add(new Items("373:16425", "Strength Splash II (1:07)"))
                .add(new Items("373:16428", "Harming Splash II"))
                .add(new Items("373:16429", "Water Breathing Splash (2:15)"))
                .add(new Items("373:16430", "Invisibility Splash (2:15)"))
                .add(new Items("373:16449", "Regeneration Splash (1:30)"))
                .add(new Items("373:16450", "Swiftness Splash (6:00)"))
                .add(new Items("373:16451", "Fire Resistance Splash (6:00)"))
                .add(new Items("373:16452", "Poison Splash (1:30)"))
                .add(new Items("373:16454", "Night Vision Splash (6:00)"))
                .add(new Items("373:16456", "Weakness Splash (3:00)"))
                .add(new Items("373:16457", "Strength Splash (6:00)"))
                .add(new Items("373:16458", "Slowness Splash (3:00)"))
                .add(new Items("373:16461", "Water Breathing Splash (6:00)"))
                .add(new Items("373:16462", "Invisibility Splash (6:00)"))
                .add(new Items("373:16471", "Regeneration Splash II (0:16)"))
                .add(new Items("374", "Glass Bottle"))
                .add(new Items("375", "Spider Eye"))
                .add(new Items("376", "Fermented Spider Eye"))
                .add(new Items("377", "Blaze Powder"))
                .add(new Items("378", "Magma Cream"))
                .add(new Items("379", "Brewing Stand"))
                .add(new Items("380", "Cauldron"))
                .add(new Items("381", "Eye of Ender"))
                .add(new Items("382", "Glistering Melon"))
                .add(new Items("383", "Spawn Egg"))
                .add(new Items("383:50", "Spawn Creeper"))
                .add(new Items("383:51", "Spawn Skeleton"))
                .add(new Items("383:52", "Spawn Spider"))
                .add(new Items("383:54", "Spawn Zombie"))
                .add(new Items("383:55", "Spawn Slime"))
                .add(new Items("383:56", "Spawn Ghast"))
                .add(new Items("383:57", "Spawn Pigman"))
                .add(new Items("383:58", "Spawn Enderman"))
                .add(new Items("383:59", "Spawn Cave Spider"))
                .add(new Items("383:60", "Spawn Silverfish"))
                .add(new Items("383:61", "Spawn Blaze"))
                .add(new Items("383:62", "Spawn Magma Cube"))
                .add(new Items("383:65", "Spawn Bat"))
                .add(new Items("383:66", "Spawn Witch"))
                .add(new Items("383:67", "Spawn Endermite"))
                .add(new Items("383:68", "Spawn Guardian"))
                .add(new Items("383:90", "Spawn Pig"))
                .add(new Items("383:91", "Spawn Sheep"))
                .add(new Items("383:92", "Spawn Cow"))
                .add(new Items("383:93", "Spawn Chicken"))
                .add(new Items("383:94", "Spawn Squid"))
                .add(new Items("383:95", "Spawn Wolf"))
                .add(new Items("383:96", "Spawn Mooshroom"))
                .add(new Items("383:98", "Spawn Ocelot"))
                .add(new Items("383:100", "Spawn Horse"))
                .add(new Items("383:120", "Spawn Villager"))
                .add(new Items("384", "Bottle o' Enchanting"))
                .add(new Items("385", "Fire Charge"))
                .add(new Items("386", "Book and Quill"))
                .add(new Items("387", "Written Book"))
                .add(new Items("388", "Emerald"))
                .add(new Items("389", "Item Frame"))
                .add(new Items("390", "Flower Pot"))
                .add(new Items("391", "Carrot"))
                .add(new Items("392", "Potato"))
                .add(new Items("393", "Baked Potato"))
                .add(new Items("394", "Poisonous Potato"))
                .add(new Items("395", "Empty Map"))
                .add(new Items("396", "Golden Carrot"))
                .add(new Items("397", "Mob Head"))
                .add(new Items("398", "Carrot on a Stick"))
                .add(new Items("399", "Nether Star"))
                .add(new Items("400", "Pumpkin Pie"))
                .add(new Items("401", "Firework Rocket"))
                .add(new Items("402", "Firework Star"))
                .add(new Items("403", "Enchanted Book"))
                .add(new Items("404", "Redstone Comparator"))
                .add(new Items("405", "Nether Brick"))
                .add(new Items("406", "Nether Quartz"))
                .add(new Items("407", "Minecart with TNT"))
                .add(new Items("408", "Minecart with Hopper"))
                .add(new Items("409", "Prismarine Shard"))
                .add(new Items("410", "Prismarine Crystals"))
                .add(new Items("417", "Iron Horse Armor"))
                .add(new Items("418", "Gold Horse Armor"))
                .add(new Items("419", "Diamond Horse Armor"))
                .add(new Items("420", "Lead"))
                .add(new Items("421", "Name Tag"))
                .add(new Items("422", "Minecart with Command Block"))
                .add(new Items("2256", "Music Disk (13)"))
                .add(new Items("2257", "Music Disk (Cat)"))
                .add(new Items("2258", "Music Disk (Blocks)"))
                .add(new Items("2259", "Music Disk (Chirp)"))
                .add(new Items("2260", "Music Disk (Far)"))
                .add(new Items("2261", "Music Disk (Mall)"))
                .add(new Items("2262", "Music Disk (Mellohi)"))
                .add(new Items("2263", "Music Disk (Stal)"))
                .add(new Items("2264", "Music Disk (Strad)"))
                .add(new Items("2265", "Music Disk (Ward)"))
                .add(new Items("2266", "Music Disk (11)"))
                .add(new Items("2267", "Music Disk (wait)"));
    }

    private final String id, name;
    private final ItemStack item;

    private Items(String id, String name) {
        this(id, name, null);
    }

    private Items(String id, String name, ItemStack item) {
        this.id = id;
        this.name = name;
        this.item = item;

        Items.items.add(this);
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public ItemStack getItemStack() {
        return item;
    }

    public static List<Items> getAll() {
        return Collections.unmodifiableList(Items.items);
    }
    
    public static Items getById(String id) {
        for (Items item : Items.items) {
            if (item.getId().equals(id)) {
                return item;
            }
        }

        return null;
    }

    public static Items getByName(String name) {
        for (Items item : Items.items) {
            if (item.getName().equalsIgnoreCase(name)) {
                return item;
            }
        }

        return null;
    }
}
